name: AstrowayCustomer
description: The Astrology app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.8.0
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  flutter_rating_bar: ^4.0.1
  flutter_html: ^3.0.0-alpha.5
  bubble_tab_indicator: ^0.1.6
  flutter_image_slideshow: ^0.1.6
  date_format: 2.0.7
  video_player: ^2.9.1
  percent_indicator: ^4.2.3
  photo_view: ^0.14.0
  custom_clippers: ^2.0.0
  timelines: ^0.1.0
  url_launcher: ^6.3.1

  easy_localization: ^3.0.5
  flutter_inappwebview: ^6.0.0
  fluttertoast: ^8.1.1

  agora_rtm: ^1.5.9
  agora_rtc_engine: ^6.3.2

  permission_handler: ^11.3.1
  path_provider: ^2.1.4

  device_info_plus: ^9.1.2
  connectivity_plus: ^5.0.2
  http: ^1.2.2

  geocoding: ^3.0.0
  flutter_google_places_sdk: ^0.3.7

  syncfusion_flutter_pdfviewer: ^24.1.41
  store_redirect: ^2.0.1
  syncfusion_flutter_gauges: ^24.2.9

  package_info_plus: ^8.0.0
  flutter_countdown_timer: ^4.1.0

  flutter_holo_date_picker: ^1.1.0
  flutter_time_picker_spinner: ^2.0.0

  get: ^4.6.6

  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.2.1+2
  cloud_firestore: ^5.1.0
  googleapis_auth: ^1.6.0
  firebase_storage: ^12.1.0

  shared_preferences: ^2.3.1

  intl_phone_number_input: ^0.7.4
  flutter_share: ^2.0.0

  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  cached_network_image: ^3.4.0

  marquee: ^2.2.3
  audioplayers: ^5.2.1
  youtube_player_flutter: ^9.0.0

  pdf: ^3.11.0
  share_plus: ^10.0.0

  uuid: ^4.4.0
  draggable_widget: ^2.0.0
  responsive_sizer: ^3.3.0+1

  intl: any

  story_view: ^0.16.5
  swipe_to: ^1.0.6
  file_picker: ^8.0.0+1
  open_file: ^3.3.2
  lecle_yoyo_player: ^0.0.8
  otpless_flutter: ^2.1.4
  pin_input_text_field: ^4.5.1
  flutter_callkit_incoming: ^2.0.4+1
  get_storage: ^2.1.1
  logger: ^2.4.0
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  screenshot: ^3.0.0
  sms_autofill: ^2.4.1
  razorpay_flutter: ^1.4.0
#  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/ringtone.mp3
    - lib/utils/noti_service.json
    - assets/fonts/NotoSans-Regular.ttf
    - assets/fonts/NotoSansTamil-Regular.ttf
    - assets/fonts/NotoSansMalayalam-Regular.ttf
    - assets/fonts/NotoSansDevanagari-Regular.ttf
    - assets/fonts/materialicons-regular.otf
    - assets/fonts/NotoColorEmoji.ttf


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: NotoSansTamil
      fonts:
        - asset: assets/fonts/NotoSansTamil-Regular.ttf
    - family: NotoSansMalayalam
      fonts:
        - asset: assets/fonts/NotoSansMalayalam-Regular.ttf
    - family: NotoSansDevanagari
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-Regular.ttf
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/materialicons-regular.otf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"
