android.useAndroidX=true
android.enableJetifier=true

# Gradle JVM (stable for Windows + Java 17)
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8 -XX:+UseParallelGC

android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false

# Java 17 path (OK)
#org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.7.7-hotspot
