// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjThV41crAEVSyqB31GJwSlDn3eK7otSE',
    appId: '1:104464591304:android:40980a3ac0db2ef7ca38fd',
    messagingSenderId: '104464591304',
    projectId: 'jyotishi-customer-2025',
    storageBucket: 'jyotishi-customer-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMNgtGentNGmVtPS4JnKgtJsGMK0k5zsU',
    appId: '1:104464591304:ios:57e2b8dc26c0387bca38fd',
    messagingSenderId: '104464591304',
    projectId: 'jyotishi-customer-2025',
    storageBucket: 'jyotishi-customer-2025.firebasestorage.app',
    iosBundleId: 'com.jyotishi2025.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMNgtGentNGmVtPS4JnKgtJsGMK0k5zsU',
    appId: '1:104464591304:ios:b24d7c5a961a8977ca38fd',
    messagingSenderId: '104464591304',
    projectId: 'jyotishi-customer-2025',
    storageBucket: 'jyotishi-customer-2025.firebasestorage.app',
    iosBundleId: 'none',
  );
}
